### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SheaML** [pblischak/HyDe#1]
Hi, 

I'm getting the folllowing error when I try "pip install phyde" or "python setup.py install". I installed the dependencies also using pip. Python 2.7.12, Xubuntu 16.04. 

----------------------------------------------------
Collecting phyde
  Using cached phyde-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    make: Nothing to be done for 'all'.
    Testing hyde_cpp compilation...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_022s5/phyde/setup.py", line 78, in <module>
        ext_modules=cythonize("phyde/**/*.pyx", compiler_directives={'--cplus': True}),
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 886, in cythonize
        c_options = CompilationOptions(**options)
      File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 568, in __init__
        raise ValueError(message)
    ValueError: got unknown compiler directive: --cplus
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_022s5/phyde/

**Comment by pblischak** [comment]
This looks like an issue with the Cython compilation of the `data.pyx` module. Do you have the latest version of Cython? Also, are you running `python setup.py install` using a clone of the repo from GitHub?

**Comment by SheaML** [comment]
Hi Paul,

I'm using an up-to-date clone of the github repo. Pip says that my Cython installation is up-to-date as well. 
I should mention that I'm also having this issue on our University HPC.

**Comment by pblischak** [comment]
I just changed the `setup.py` file to build and compile the `data.pyx` module in a different way. If you pull these changes into your clone of the repo and give `python setup.py install` another try hopefully it will work. Let me know if you get the same error though.

**Comment by SheaML** [comment]
That seems to have fixed it! Many thanks. I will close the issue. 

Shea
