### ISSUE TITLE
issue running setup.py install

### ISSUE THREAD

**Issue by angelajmcd** [pblischak/HyDe#12]
Hi Paul,

I've been attempting to use HyDe with both python 2 and python 3 (at different times, of course) and I've gotten this error while running setup.py:

AngJMcD:HyDe angelarein$ python3 setup.py install
Compiling phyde/core/data.pyx because it depends on /Users/angelarein/miniconda3/lib/python3.7/site-packages/Cython/Includes/numpy/__init__.pxd.
[1/1] Cythonizing phyde/core/data.pyx
/Users/angelarein/miniconda3/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Applications/HyDe/phyde/core/data.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running install
running bdist_egg
running egg_info
writing phyde.egg-info/PKG-INFO
writing dependency_links to phyde.egg-info/dependency_links.txt
writing top-level names to phyde.egg-info/top_level.txt
reading manifest file 'phyde.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'phyde.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/phyde
copying phyde/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/phyde
creating build/lib.macosx-10.7-x86_64-3.7/phyde/core
copying phyde/core/bootstrap.py -> build/lib.macosx-10.7-x86_64-3.7/phyde/core
copying phyde/core/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/phyde/core
copying phyde/core/result.py -> build/lib.macosx-10.7-x86_64-3.7/phyde/core
copying phyde/core/utils.py -> build/lib.macosx-10.7-x86_64-3.7/phyde/core
creating build/lib.macosx-10.7-x86_64-3.7/phyde/visualize
copying phyde/visualize/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/phyde/visualize
copying phyde/visualize/viz.py -> build/lib.macosx-10.7-x86_64-3.7/phyde/visualize
running build_ext
building 'phyde.core.data' extension
creating build/temp.macosx-10.7-x86_64-3.7
creating build/temp.macosx-10.7-x86_64-3.7/phyde
creating build/temp.macosx-10.7-x86_64-3.7/phyde/core
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/angelarein/miniconda3/include -arch x86_64 -I/Users/angelarein/miniconda3/include -arch x86_64 -I/Users/angelarein/miniconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/angelarein/miniconda3/include/python3.7m -c phyde/core/data.cpp -o build/temp.macosx-10.7-x86_64-3.7/phyde/core/data.o
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on
      the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
In file included from phyde/core/data.cpp:632:
In file included from /Users/angelarein/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/angelarein/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /Users/angelarein/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:
/Users/angelarein/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: 
      "Using deprecated NumPy API, disable it with "          "#define
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
phyde/core/data.cpp:635:10: fatal error: 'ios' file not found
#include "ios"
         ^~~~~
2 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1

Any recommendations about how to work around this? I've completed software updates and ensured numpy is up to date... I'm not sure at all about what to do about missing stdlibc++ headers... (or even what that means, really!)

Let me know what you think,
Angela

**Comment by angelajmcd** [comment]
An update: I *think* I might have fixed the issue, for now.

I think I found/installed headers using this:
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

I then still kept getting the gcc failed error, so I ran the following:
export MACOSX_DEPLOYMENT_TARGET=10.10
CFLAGS='-stdlib=libc++' python setup.py install

It looks like it is running now. The files it's making are still 0 bytes, so not 100% sure yet.

**Comment by pblischak** [comment]
Hi Angela,

I've gotten this error before too and it is a weird one that is associated with using macOS Mojave and the version of Xcode that you have (at least I'm pretty sure). It looks like you are using Python 3.7, which is the one I used as well, and I used the `CFLAGS='--stdlib=c++' python setup.py install` command as well. I didn't set the `MACOSX_DEPLOYMENT_TARGET=10.10` command though. You might try seeing if the tests run correctly. You can run them by going into the HyDe folder that you cloned from GitHub and typing `make`. If the tests work then everything should be good. Let me know how everything goes though.

Paul

**Comment by angelajmcd** [comment]
Hey Paul,

I ran it through the test dataset successfully. It is still chugging through the 10k+ triples for a real analysis; the files it's making there are still at 0 kb. Probably just running slow.

Thanks!
