### ISSUE TITLE
"number of sites specified is not equal to number of sites in data file"

### ISSUE THREAD

**Issue by rakeuler** [pblischak/HyDe#20]
Hi, I'm getting a confusing error, and I'm not sure what to do about it. My files have 515571 sites but won't accept that input. I've attached a screenshot where all I've done is changed the number after -s.
![image](https://user-images.githubusercontent.com/64653318/111176093-a5d49000-856e-11eb-87a3-00af64ed8fe9.png)
Thanks,
Rachel

**Comment by pblischak** [comment]
Hi Rachel,

Is the data file that you're using in Phylip format (with the number of individuals and number of sites at the top)? HyDe tries to do some spot checking to make sure that everything matches up in the input matrix. That's definitely a little strange that it switches depending on which number you use for the `-n` flag, though. Do all the rows in your input file have the same number of sites?

Paul
