### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by bmichanderson** [pblischak/HyDe#23]
I'm not sure, but shouldn't this be 15: [0, 1, 2, 3] ?
https://github.com/pblischak/HyDe/blob/48121838ce021f58fe7ecf6e6d7a8bb68464e2a3/phyde/core/data.pyx#L48

**Comment by pblischak** [comment]
Thanks for finding that bug! I'll be sure to change it ASAP

**Comment by pblischak** [comment]
Closing now that his has been fixed
