### ISSUE TITLE
Does HyDe could identify Degenerte Nucleotide Codes?

### ISSUE THREAD

**Issue by zhangzhiyangcs** [pblischak/HyDe#25]
Hi,
    Thanks very useful software, Does HyDe could identify Degenerte Nucleotide Codes? I covert allele 0/1 as following Degenerte Nucleotide Codes rules.
R = | A,G
Y = | C,T
M = | A,C
K = | G,T
S = | C, G
W = | A,T
H = | A,C,T
B = | C,G,T
V = | A,C,G
D = | A,G,T
N = | A,C,G,T

**Comment by pblischak** [comment]
HyDe does support degenerate nucleotide codes so you should be able to include them in your input data without any problems. Let me know if you have any issues though

**Comment by zhangzhiyangcs** [comment]
Okay, Thanks a lot.
