### ISSUE TITLE
Different order of map.txt generate different results

### ISSUE THREAD

**Issue by zhangzhiyangcs** [pblischak/HyDe#27]
Hi,
    When I change the order of map.txt. Hyde generate different results below.  The other data is totally same. Which results should I choose? 1) map.txt corespond to 1) hyde result. Thanks a lot.

##1) map.txt 
A1    PP
A2    PP
B1    EE
B2    EE
C1     TT
C1   TT
out Outgroup

##2) map.txt
A1    PP
A2    PP
B1    EE
B2    EE
out Outgroup
C1     TT
C1   TT

##3) map.txt
A1    PP
A2    PP
out Outgroup
B1    EE
B2    EE
C1     TT
C1   TT

###1) hyde result
P1      Hybrid  P2      Zscore              Pvalue  Gamma                AAAA         AAAB        AABA        AABB       AABC       ABAA        ABAB       ABAC       ABBA       BAAA       ABBC      CABC      BACA      BCAA      ABCD
PP  EE     TT  -99999.9            1.0     -0.6460759167691903  239310514.0  4926153.0   18118082.0  5267407.0  1050209.0  2101676.0   1764620.0  117080.0   389795.0   3519108.0  109741.0  224078.0  592437.0  233609.0  35727.0
PP  TT  EE     314.8021752685754   0.0     0.21988626194874097  239310514.0  18118082.0  4926153.0   5267407.0  1050209.0  2101676.0   389795.0   224078.0   1764620.0  3519108.0  592437.0  117080.0  109741.0  233609.0  35727.0
EE     PP  TT  -802.0547830469242  1.0     0.582026225720279    239310514.0  4926153.0   2101676.0   1764620.0  117080.0   18118082.0  5267407.0  1050209.0  389795.0   3519108.0  109741.0  224078.0  233609.0  592437.0  35727.0

###2) hyde result
P1      Hybrid  P2      Zscore               Pvalue  Gamma                 AAAA         AAAB        AABA        AABB       AABC       ABAA        ABAB       ABAC       ABBA       BAAA       ABBC      CABC      BACA      BCAA      ABCD
PP  EE     TT  -99999.9             1.0     -0.36171008725438364  238693380.0  5203504.0   18077744.0  5788436.0  1161575.0  1840380.0   1482371.0  102253.0   338554.0   3072035.0  105226.0  192061.0  518217.0  203247.0  32078.0
PP  TT  EE     289.6934294867369    0.0     0.17347121850724456   238693380.0  18077744.0  5203504.0   5788436.0  1161575.0  1840380.0   338554.0   192061.0   1482371.0  3072035.0  518217.0  102253.0  105226.0  203247.0  32078.0
EE     PP  TT  -1090.5929335224123  1.0     0.5586215259266988    238693380.0  5203504.0   1840380.0   1482371.0  102253.0   18077744.0  5788436.0  1161575.0  338554.0   3072035.0  105226.0  192061.0  203247.0  518217.0  32078.0

##3) hyde result
P1      Hybrid  P2      Zscore              Pvalue  Gamma                AAAA         AAAB       AABA       AABB       AABC      ABAA       ABAB       ABAC      ABBA       BAAA        ABBC       CABC      BACA       BCAA       ABCD
PP  EE     TT  33.290576652603384  0.0     0.2156890547043237   225766655.0  4715721.0  4476232.0  2528479.0  208190.0  2942980.0  1908951.0  159003.0  2079324.0  27485012.0  1115630.0  162031.0  1032858.0  887788.0   63979.0
PP  TT  EE     -99999.9            1.0     -0.6111334304223373  225766655.0  4476232.0  4715721.0  2528479.0  208190.0  2942980.0  2079324.0  162031.0  1908951.0  27485012.0  1032858.0  159003.0  1115630.0  887788.0   63979.0
EE     PP  TT  -87.76407621160669  1.0     0.42028833620446854  225766655.0  4715721.0  2942980.0  1908951.0  159003.0  4476232.0  2528479.0  208190.0  2079324.0  27485012.0  1115630.0  162031.0  887788.0   1032858.0  63979.0

**Comment by zhangzhiyangcs** [comment]
My command "python ~/software/hybrid/HyDe/scripts/run_hyde.py  -i tmp -m tmp.ID -o Outgroup -n 7  -t 10  -s 37366245".

**Comment by pblischak** [comment]
HyDe expects the taxa/individuals in the map to be in the same order as they are in the Phylip file with your sequence data and the results can be slightly different if not. The correct result would be the one where the map and the sequence data are in the same order

**Comment by zhangzhiyangcs** [comment]
After change the correct order, I get the stable results. Thanks a lot.
