### ISSUE TITLE
please，what function these ？Does it  affect the results？ 

### ISSUE THREAD

**Issue by yuanjigui** [pblischak/HyDe#34]
AAAA	AAAB	AABA	AABB	AABC	ABAA	ABAB	ABAC	ABBA	BAAA	ABBC	CABC	BACA	BCAA	ABCD

**Comment by pblischak** [comment]
see #37

**Comment by yuanjigui** [comment]
Dear professor


I have a question for hyde analysis，i do not know why i got different results when i used different sp4 (in the results of&nbsp;Hyde2 and&nbsp;Hyde3, they used different sp4). And in the result of Hyde2 package, can i considered the sp3 was the hybrides of sp1 and sp2?






------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "pblischak/HyDe"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Apr 6, 2023 02:36 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [pblischak/HyDe] please，what function these ？Does it  affect the results？  (Issue #34)





 
Closed #34 as completed.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Hyde2.zip (104.44M, 2023年05月25日 16:53 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0e3536304e8f48cd294321731761021b48410456525008571d0c0407074c015204021b0608500619070302045351085207040f553168307c495153021f1b59443008&code=05601a04




Hyde3.zip (176.15M, 2023年05月25日 16:53 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=58303263c3b0ccc17f4625201236031a1e440a510d0f01064b040b55521b545105561f5b0253081857030b010c04045653025750343f317d1f5457501a4c5845660d&code=f02c4615

**Comment by yuanjigui** [comment]
Dear professor,&nbsp;I will really appreciate it if you tell me that can i considered the sp3 was the hybrids of sp1 and sp2 in this result. Why the result has many 0 and nan.&nbsp;













------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "袁吉贵"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Apr 25, 2023 04:55 PM
***@***.******@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;Re: [pblischak/HyDe] please，what function these ？Does it  affect the results？  (Issue #34)



Dear professor


I have a question for hyde analysis，i do not know why i got different results when i used different sp4 (in the results of Hyde2 and Hyde3, they used different sp4). And in the result of Hyde2 package, can i considered the sp3 was the hybrides of sp1 and sp2?






------------------ Original ------------------
From:                                                                                                                        "pblischak/HyDe"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Apr 6, 2023 02:36 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [pblischak/HyDe] please，what function these ？Does it  affect the results？  (Issue #34)





 
Closed #34 as completed.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



从QQ邮箱发来的超大附件

result.zip (78.55M, 2023年05月26日 18:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5d353836510123997b432f754538064d1a415b01055905564f500a025b150252040d150f020f574f5b040c045a000556530c59506332341007464d5a17164e0b123505&code=b586c84b
