### ISSUE TITLE
Exception KeyError

### ISSUE THREAD

**Issue by stsmall** [pblischak/HyDe#4]
Hi,
I keep getting an error when running HyDe. It is definitely something with my input files as I do not return the same error when I run on the snake data in examples. The online docs mention phylip format, does this include relaxed format? If not then likely that the name length is my issue.
thanks,

**head input.phy**
funestus4590C5Kenya ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCATTTCCTAATG
funestuscfMALAF1057SouthAfrica ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCC
funestuscfMALAF10711Kwa ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCATTTCCT
funestuscfMALAF994SouthAfrica ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCA
funestuscfMALF90Kwa ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCATTTCCTAATG
funestuscfMALF982SouthAfrica ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCAT
funestusF220Moz ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCATTTCCTAATGCTTT
funestusGhaF264Ghana ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCATTTCCTAAT
funestusGhaF265Ghana ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCATTTCCTAAT
funestusMozF123Mozambique ATTATCGGTCGCTTACTGCTAGCAAATTCCTGCACCGATTTATGCCAGCATACCACGAGAAAATACGCCATTTC

**head map.txt**
funestus4590C5Kenya     FUN
funestuscfMALAF1057SouthAfrica  LIK
funestuscfMALAF10711Kwa LIK
funestuscfMALAF994SouthAfrica   LIK
funestuscfMALF90Kwa     LIK
funestuscfMALF982SouthAfrica    LIK
funestusF220Moz FUN
funestusGhaF264Ghana    FUN
funestusGhaF265Ghana    FUN
funestusMozF123Mozambique       FUN

Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
Reading input file.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Exception KeyError: ('c',) in 'phyde.core.data.HydeData._convert' ignored
.Done.

**Comment by pblischak** [comment]
Hi Scott,

Are the sequence names and the sequence data on separate lines for each sample for the input.phy file? Also, it looks like the populations that your samples belong to are not all listed together. So, for your data, you would need to have all of the FUN samples listed next to one another, then the LIK samples, etc. On top of this, the sequences in the input.phy file need to be in the same order as in the map file. Please let me know if that works

**Comment by stsmall** [comment]
The samples are in the same order between the map and infile.phy, I regrouped the POP names so they are in blocks as well. Unfortunately neither of those things resolved the error. I also tried to shorten the names but that didnt work either. The samples and sequence are on the same line, I am not sure why it looks like that in the comment. Any ideas on what I should try?
thanks!!

**Comment by stsmall** [comment]
The lowercase patch fixed it. Now on to make sense of the output! Thank you!
