### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by RSchley** [pblischak/HyDe#5]
Hi there,

When I try to run run_hyde.py like this:
python /mnt/HDD_3/rschley/Brownea_phylogenomics/Programs/HyDe/scripts/run_hyde.py -i gene54356.FNA.aligned.txt -o Macrolobium_herrerae_S24_L001 -m Taxon_map.txt -n 39 -s 5617 -t 27

I get the following error:

_Running run_hyde.py

Reading input file.......................................Done.
**zsh: segmentation fault  python  -i gene54356.FNA.aligned.txt -o Macrolobium_herrerae_S24_L001 -m  -n**_

Any idea on how to fix this?

Thanks a lot,
Rowan

**Comment by pblischak** [comment]
Hi Rowan,

I'm not 100% sure of what could be causing it, but it may be an issue with the format of the input files. It looks like the issue was with reading in the map file. If you want to send me your data I can take a look at it and troubleshoot from there: paul.blischak@gmail.com

Thanks!

**Comment by TiagoBelintani** [comment]
Hi, i have the same problem. Please help me.

**Comment by pblischak** [comment]
Hi @TiagoBelintani -- segmentation faults are usually an issue with file formatting or the ordering of taxa in the map file. The map has to be in the same order as the phylip file and the individuals in each population have to be listed sequentially for both. If you want some extra help with the data formatting feel free to send me your input files and I'll take a look at them if you're okay with that. Thanks!

**Comment by TiagoBelintani** [comment]
Hi @pblischak I will go send ([paul.blischak@gmail.com](mailto:paul.blischak@gmail.com). Thanks.
