### ISSUE TITLE
Installation error - seaborn missing

### ISSUE THREAD

**Issue by ethering** [pblischak/HyDe#7]
Hi,
I've tried this on Linux and Mac and get the same error.
I've used `pip install` to install dependencies

`$ pip install cython numpy matplotlib seaborn multiprocess`

Looks like everything worked OK

```
Installing collected packages: cython, numpy, matplotlib, seaborn, multiprocess
Successfully installed cython-0.29.4 matplotlib-3.0.2 multiprocess-0.70.7 numpy-1.16.1 seaborn-0.9.0
```
Now install phyde

```
$ pip install phyde
Collecting phyde
  Downloading https://files.pythonhosted.org/packages/fc/20/4d9bc5157ad9f099db673f752d32191005a01429a0eab831d7d09a41e533/phyde-0.4.2.tar.gz (659kB)
    100% |████████████████████████████████| 665kB 5.2MB/s 
    Complete output from command python setup.py egg_info:
    ERROR:
      You are missing the following required modules:
      	 seaborn
    
    
    ERROR:
      Unable to install phyde.
      Please see the documentation at http://hybridization-detection.rtfd.io/.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 255 in /private/var/folders/nn/mky1r73s295cp1qbt_z8pls0ppkbr7/T/pip-install-2j_9yzs6/phyde/
```
The same thing happens when I try to git clone and install. 
I've reinstall seaborn independently, both through pip and git (installations finish successfully), but I get the same 'seaborn missing' error when I try to install phyde.
Have you seen this problem before or do you have any suggestions?
Many thanks,
Graham

**Comment by ethering** [comment]
Hi Paul,
Thanks for the advice. I tried again on Mac, using a virtualenv. I initially ran into a problem during phyde installation with matplotlib:
`RuntimeError: Python is not installed as a framework.....`

but found the following fix:
`echo "backend: TkAgg" >> ~/.matplotlib/matplotlibrc`

phyde then installed successfully and everything now runs fine.
Many thanks,
Graham

**Comment by pblischak** [comment]
Ok cool -- glad things are working for you! I'm going to go ahead and close this, but please feel free to reopen it if any other issues arise
